[package]
name = "pilots-intent"
version = "0.1.0"
edition = "2024"

[dependencies]
nalgebra = { version = "0.34.1", default-features = false, features = ["std"] }
num-complex = "0.4"
plotters = "0.3.7"
